// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: otp.proto

package otp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// validate otp create account
type ValidateCreateAccountDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Otp           string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCreateAccountDto) Reset() {
	*x = ValidateCreateAccountDto{}
	mi := &file_otp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCreateAccountDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCreateAccountDto) ProtoMessage() {}

func (x *ValidateCreateAccountDto) ProtoReflect() protoreflect.Message {
	mi := &file_otp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCreateAccountDto.ProtoReflect.Descriptor instead.
func (*ValidateCreateAccountDto) Descriptor() ([]byte, []int) {
	return file_otp_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateCreateAccountDto) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ValidateCreateAccountDto) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

// validate response
type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_otp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_otp_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_otp_proto protoreflect.FileDescriptor

const file_otp_proto_rawDesc = "" +
	"\n" +
	"\totp.proto\x12\x03otp\"B\n" +
	"\x18ValidateCreateAccountDto\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x10\n" +
	"\x03otp\x18\x02 \x01(\tR\x03otp\"-\n" +
	"\x10ValidateResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid2[\n" +
	"\n" +
	"OtpService\x12M\n" +
	"\x15ValidateCreateAccount\x12\x1d.otp.ValidateCreateAccountDto\x1a\x15.otp.ValidateResponseB\rZ\v./proto/otpb\x06proto3"

var (
	file_otp_proto_rawDescOnce sync.Once
	file_otp_proto_rawDescData []byte
)

func file_otp_proto_rawDescGZIP() []byte {
	file_otp_proto_rawDescOnce.Do(func() {
		file_otp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_otp_proto_rawDesc), len(file_otp_proto_rawDesc)))
	})
	return file_otp_proto_rawDescData
}

var file_otp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_otp_proto_goTypes = []any{
	(*ValidateCreateAccountDto)(nil), // 0: otp.ValidateCreateAccountDto
	(*ValidateResponse)(nil),         // 1: otp.ValidateResponse
}
var file_otp_proto_depIdxs = []int32{
	0, // 0: otp.OtpService.ValidateCreateAccount:input_type -> otp.ValidateCreateAccountDto
	1, // 1: otp.OtpService.ValidateCreateAccount:output_type -> otp.ValidateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_otp_proto_init() }
func file_otp_proto_init() {
	if File_otp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_otp_proto_rawDesc), len(file_otp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_otp_proto_goTypes,
		DependencyIndexes: file_otp_proto_depIdxs,
		MessageInfos:      file_otp_proto_msgTypes,
	}.Build()
	File_otp_proto = out.File
	file_otp_proto_goTypes = nil
	file_otp_proto_depIdxs = nil
}
