// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// inventory
type InventoryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AvailableStock int64                  `protobuf:"varint,2,opt,name=available_stock,json=availableStock,proto3" json:"available_stock,omitempty"`
	ReservedStock  int64                  `protobuf:"varint,3,opt,name=reserved_stock,json=reservedStock,proto3" json:"reserved_stock,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InventoryResponse) Reset() {
	*x = InventoryResponse{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryResponse) ProtoMessage() {}

func (x *InventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryResponse.ProtoReflect.Descriptor instead.
func (*InventoryResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *InventoryResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InventoryResponse) GetAvailableStock() int64 {
	if x != nil {
		return x.AvailableStock
	}
	return 0
}

func (x *InventoryResponse) GetReservedStock() int64 {
	if x != nil {
		return x.ReservedStock
	}
	return 0
}

// product message
type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Convert từ hex string của ObjectID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"` // Dùng string để giữ độ chính xác của Decimal128
	Attributes    *structpb.Struct       `protobuf:"bytes,4,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Images        []string               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	InventoryInfo *InventoryResponse     `protobuf:"bytes,7,opt,name=inventory_info,json=inventoryInfo,proto3" json:"inventory_info,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductResponse) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *ProductResponse) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ProductResponse) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ProductResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ProductResponse) GetInventoryInfo() *InventoryResponse {
	if x != nil {
		return x.InventoryInfo
	}
	return nil
}

func (x *ProductResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// create product dto
type CreateProductDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         string                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	Attributes    *structpb.Struct       `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Images        []string               `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	Quantity      int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductDto) Reset() {
	*x = CreateProductDto{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductDto) ProtoMessage() {}

func (x *CreateProductDto) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductDto.ProtoReflect.Descriptor instead.
func (*CreateProductDto) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProductDto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductDto) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *CreateProductDto) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CreateProductDto) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateProductDto) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// get list
type GetListProductDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	OrderBy       string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Sort          string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListProductDto) Reset() {
	*x = GetListProductDto{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListProductDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListProductDto) ProtoMessage() {}

func (x *GetListProductDto) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListProductDto.ProtoReflect.Descriptor instead.
func (*GetListProductDto) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *GetListProductDto) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListProductDto) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetListProductDto) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *GetListProductDto) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

// list product response
type ListProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ProductResponse     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int64                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	HasNext       bool                   `protobuf:"varint,5,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	HasPrev       bool                   `protobuf:"varint,6,opt,name=has_prev,json=hasPrev,proto3" json:"has_prev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductResponse) Reset() {
	*x = ListProductResponse{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductResponse) ProtoMessage() {}

func (x *ListProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductResponse.ProtoReflect.Descriptor instead.
func (*ListProductResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *ListProductResponse) GetItems() []*ProductResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListProductResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProductResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProductResponse) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *ListProductResponse) GetHasPrev() bool {
	if x != nil {
		return x.HasPrev
	}
	return false
}

// find by id
type FindByIdDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdDto) Reset() {
	*x = FindByIdDto{}
	mi := &file_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdDto) ProtoMessage() {}

func (x *FindByIdDto) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdDto.ProtoReflect.Descriptor instead.
func (*FindByIdDto) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5}
}

func (x *FindByIdDto) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\aproduct\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"s\n" +
	"\x11InventoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0favailable_stock\x18\x02 \x01(\x03R\x0eavailableStock\x12%\n" +
	"\x0ereserved_stock\x18\x03 \x01(\x03R\rreservedStock\"\xf2\x02\n" +
	"\x0fProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x127\n" +
	"\n" +
	"attributes\x18\x04 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12\x16\n" +
	"\x06images\x18\x05 \x03(\tR\x06images\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12A\n" +
	"\x0einventory_info\x18\a \x01(\v2\x1a.product.InventoryResponseR\rinventoryInfo\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa9\x01\n" +
	"\x10CreateProductDto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x127\n" +
	"\n" +
	"attributes\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12\x16\n" +
	"\x06images\x18\x04 \x03(\tR\x06images\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\"l\n" +
	"\x11GetListProductDto\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\"\xbb\x01\n" +
	"\x13ListProductResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.product.ProductResponseR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\x12\x19\n" +
	"\bhas_next\x18\x05 \x01(\bR\ahasNext\x12\x19\n" +
	"\bhas_prev\x18\x06 \x01(\bR\ahasPrev\",\n" +
	"\vFindByIdDto\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId2\xde\x01\n" +
	"\x0eProductService\x12D\n" +
	"\rCreateProduct\x12\x19.product.CreateProductDto\x1a\x18.product.ProductResponse\x12J\n" +
	"\x0eGetListProduct\x12\x1a.product.GetListProductDto\x1a\x1c.product.ListProductResponse\x12:\n" +
	"\bFindById\x12\x14.product.FindByIdDto\x1a\x18.product.ProductResponseB\x11Z\x0f./proto/productb\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_product_proto_goTypes = []any{
	(*InventoryResponse)(nil),     // 0: product.InventoryResponse
	(*ProductResponse)(nil),       // 1: product.ProductResponse
	(*CreateProductDto)(nil),      // 2: product.CreateProductDto
	(*GetListProductDto)(nil),     // 3: product.GetListProductDto
	(*ListProductResponse)(nil),   // 4: product.ListProductResponse
	(*FindByIdDto)(nil),           // 5: product.FindByIdDto
	(*structpb.Struct)(nil),       // 6: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_product_proto_depIdxs = []int32{
	6, // 0: product.ProductResponse.attributes:type_name -> google.protobuf.Struct
	0, // 1: product.ProductResponse.inventory_info:type_name -> product.InventoryResponse
	7, // 2: product.ProductResponse.created_at:type_name -> google.protobuf.Timestamp
	7, // 3: product.ProductResponse.updated_at:type_name -> google.protobuf.Timestamp
	6, // 4: product.CreateProductDto.attributes:type_name -> google.protobuf.Struct
	1, // 5: product.ListProductResponse.items:type_name -> product.ProductResponse
	2, // 6: product.ProductService.CreateProduct:input_type -> product.CreateProductDto
	3, // 7: product.ProductService.GetListProduct:input_type -> product.GetListProductDto
	5, // 8: product.ProductService.FindById:input_type -> product.FindByIdDto
	1, // 9: product.ProductService.CreateProduct:output_type -> product.ProductResponse
	4, // 10: product.ProductService.GetListProduct:output_type -> product.ListProductResponse
	1, // 11: product.ProductService.FindById:output_type -> product.ProductResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
